VictoryFairy/VictoryFairy-frontEnd

.eslintrc.cjs
package-lock.json
package.json
tsconfig.app.json

ESLint 에어비앤비 스타일을 추가하고, rules를 추가하였습니다.
바로 머지하지말고 해당 브랜치 pull하고 테스트 후 머지하면 될 거 같아요
설정 > 확장 > ESLint > settings.json 들어가서 편집 해야함
해당 코드 추가
```json
// settings.json
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true
},
```

[Config] ESLint 에어비앤비 추가

---

package-lock.json
package.json

This PR includes library settings and configuration updates.
Fixes #8

Library setting #8

---

.eslintrc.cjs
package-lock.json
package.json
src/style/global.ts
src/style/typography.ts

타이포그래피 및 전역 컬러를 추가하였습니다
```tsx
const HomeStyle = styled.div`
background-color: var(--green-500);
${typography.headline};
`;
```

[Design] 디자인 시스템 추가

---

package-lock.json
package.json
src/components/common/Footer.tsx
src/components/common/Header.tsx
src/components/layout/Layout.tsx
src/pages/Home.tsx
src/pages/Login.tsx
src/pages/PasswordReset.tsx
src/pages/Signup.tsx

padding css 설정 및 background설정
closes #42

Feature/#42 padding및 css설정

---

src/App.tsx
src/components/common/Footer.tsx
src/components/mypage/Profile.tsx
src/components/mypage/ProfileButtons.tsx
src/pages/MyPage.tsx

마이페이지 css구현
-> 추후에 공통 버튼 컴포넌트 만들어서 사용예정
closes #44

Feature/#44 마이페이지 css구현

---

package.json

모바일 환경에서 접속 가능한 스크립트 추가
모바일에서 네트워크 주소 입력하고 접속하시면 됩니다. 
저희는 모바일 서비스이다보니, 모바일 환경으로 확인을 필수로 하여 작업해야합니다

Chore/#39 모바일 환경에서 접속 가능한 스크립트 추가

---

index.html

- 모바일 환경에서 input 클릭 시 확대되는 이슈 방지

Fix/#41 모바일에서 input 확대 되는 버그

---

src/vite-env.d.ts

Chore/#51 svg import 에러

---

src/App.tsx
src/components/common/Footer.tsx
src/components/common/Tabs.tsx
src/context/ThemeContext.tsx
src/main.tsx
src/style/theme.ts

Tab 기능을 구현하였습니다.
direction에 따라 가로 세로가 바뀝니다.
```tsx
const [activeTab, setActiveTab] = useState(0);
const renderContent = () => {
switch (activeTab) {
case 0:
return <div>승률</div>;
case 1:
return <div>내 직관</div>;
default:
return null;
}
};
return (
<MainContainer>
<Tabs
labels={["승률", "내 직관"]}
activeTab={activeTab}
onTabClick={setActiveTab}
direction='column'
/>
{renderContent()}
</MainContainer>
);
```
closes #55

Feat/#54 Tabs 컴포넌트 추가

---

src/components/watchList/WatchList.tsx
src/style/global.ts

🔧 글로벌스타일 unset 삭제

---

src/components/modal/Popup.tsx
src/components/mypage/ProfileButtons.tsx
src/hooks/usePopup.tsx

confirmMessage , confirmFunc추가
```typescript
interface PopupProps {
title: string;
message: string;
closePopup: () => void;
type: "confirm" | "alert";
confirmMessage?: string;
confirmFunc?: () => void;
}
```
예시
해당 로그아웃 클릭시에 alert함수 실행됨
closes #65

Chore/#65 공통 모달 컴포넌트 수정

---

src/components/common/Text.tsx

Text 공통 컴포넌트 추가
- as로 html tag를 받아서 사용하게 하였습니다.
- variant로 타이포그래피가 적용 되게 하였습니다.
```tsx
type TextTags = "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "span";
interface TextProps extends Omit<React.HTMLAttributes<HTMLElement>, "as"> {
as?: Extract<React.ElementType, TextTags>;
variant?: keyof typeof typography;
children: React.ReactNode;
}
const Text = ({ variant = "body_01", as = "span", children }: TextProps) => {
return (
<TextComponent as={as} variant={variant}>
{children}
</TextComponent>
);
};
```
closes #70

Feat/#70 Text 공통 컴포넌트 추가

---

src/components/common/Button.tsx
src/components/passwordReset/VerificationCode.tsx
src/components/signup/EmailValid.tsx
src/components/signup/VerificationCode.tsx
src/pages/Home.tsx
src/style/button.ts

버튼 공통 컴포넌트를 멘토링에서 배운 내용을 바탕으로 
`React.ButtonHTMLAttributes<HTMLButtonElement` 이용해서 버튼의 역할을 다른 곳에서도 충분히 활용할 수 있도록 작성했습니다.
어려웠던 부분이 variant가 3개인데, 거기에 대해서 또 스타일이 3개로 나눠지니까 복잡하게 느껴졌네요.
button.ts에서 버튼css를 여러개 추가 후 import해서 사용하는데 이 방법도 좋은 방법인지 몰라서 같이 좀 더 살펴 봤으면 좋겠습니다
closes #74

Chore/#74 버튼 공통 컴포넌트 수정

---

src/api/info/info.api.ts
src/components/info/map/Map.tsx
src/components/info/map/ParkingInfoPage.tsx
src/components/info/map/ParkingList.tsx
src/components/info/map/StadiumList.tsx
src/components/layout/Layout.tsx
src/pages/Info.tsx
src/types/Stadium.ts

Feat/#82 지도 페이지 완성

---

src/components/common/Calendar.tsx
src/components/common/MonthNav.tsx
src/components/watchList/GalleryTab/GalleryTab.tsx
src/components/watchList/GameListItem.tsx
src/components/watchList/ListTab.tsx
src/components/watchList/ResultLabel.tsx
src/components/watchList/WatchList.tsx
src/types/Game.ts

Feat/#95 내 직관 - 갤러리 컴포넌트 UI

---

src/App.tsx
src/components/info/map/LocationButton.tsx
src/components/info/map/ParkingList.tsx

Feat/#101 지도페이지 svg추가

---

src/components/ranking/RankingTab.tsx

Chore/#105 랭킹페이지 공통컴포넌트들로 변경

---

src/components/mypage/Profile.tsx
src/components/mypage/ProfileButtons.tsx
src/components/mypage/ProfileChange.tsx
src/components/mypage/TeamChange.tsx
src/pages/MyPage.tsx

Chore/#108 마이페이지 공통 컴포넌트로 변경

---

.eslintrc.cjs
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx

모달 구현
쓸어내리기 구현
바깥쪽 클릭시 모달 닫기 구현
closes #114 
https://github.com/user-attachments/assets/aedc1220-2471-43e2-9cd6-56f410ac1062

Feature/#114 마이페이지 모달 ui 구현

---

src/components/info/cheerSong/CheerSongList.tsx
src/pages/SearchCheerSong.tsx

Feat/#134 최신검색기록 구현

---

.eslintrc.cjs
src/components/common/OTPInput.tsx

✨ 인증번호 input 복사붙어넣기 추가

---

.env.development
index.html

Chore/#143 네이버 지도 api키 env 추가

---

.env.development
.gitignore

Chore/#149  Env파일 삭제

---

src/components/info/cheerSong/CheerSongPage.tsx

🐛 무한스크롤 리팩토링

---

.env.development
.gitignore
src/components/common/InputField.tsx
src/components/common/TextAreaField.tsx

Refactor/#151 Maxlength에 따라 입력불가, 스타일변경

---

src/App.tsx
src/pages/main/Main.tsx

직관 등록하기 버튼 테마컬러 적용
App.tsx에서 Register -> register로 변경
closes #144

Chore/#144 직관 등록하기 버튼 테마컬러 적용 

---

src/api/rank/rank.api.ts
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx
src/types/Rank.ts

랭킹 및 모달 api 연결 구현
+ 백엔드 수정 후 변경, 팀 탭 클릭시 색깔 변경 구현 예정

Feature/#137 랭킹 api 연결

---

.env.development
.gitignore
src/App.tsx
src/components/common/InputField.tsx
src/components/common/TextAreaField.tsx

Chore/#154 페이지별 레이아웃 수정

---

src/components/info/map/Map.tsx
src/components/info/map/ZoomButton.tsx

Refactor/#156 지도 중심점 이탈해결

---

src/pages/CheersongDetail.tsx
src/pages/Info.tsx

Refactor/#159 정보페이지 탭유지

---

src/App.tsx
src/api/game/game.ts
src/api/register/register.ts
src/components/common/Calendar.tsx
src/components/common/GameListItem.tsx
src/components/watchList/GalleryTab/GalleryTab.tsx
src/components/watchList/ListTab/ListTab.tsx
src/components/watchList/ListTab/ResultLabel.tsx
src/components/watchList/WatchList.tsx
src/pages/Detail.tsx
src/types/Game.ts
src/utils/uploadImg.ts

내가 등록한 직관 불러오기 API 연결.
closes #136

Feat/#136 내가 등록한 직관 불러오기 API 연결

---

src/components/info/cheerSong/CheerSongList.tsx
src/components/info/cheerSong/CheerSongPage.tsx
src/components/info/map/ParkingInfoPage.tsx
src/utils/getTeamId.ts

Refactor/#163 무한스크롤 리팩토링(멘토링)

---

src/api/info/cheers.api.ts
src/api/info/info.api.ts
src/components/info/cheerSong/CheerSongPage.tsx
src/components/info/map/StadiumList.tsx
src/pages/SearchCheerSong.tsx
src/types/Stadium.ts

Chore/#165 스네이크 케이스 => 카멜케이스 수정

---

src/App.tsx
src/components/common/InputField.tsx
src/components/signup/PasswordValid.tsx
src/store/signupStep.ts

Chore/#169 비밀번호 검증 수정

---

src/App.tsx
src/api/rank/rank.api.ts
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx
src/types/Rank.ts

랭킹 페이지 api연결
closes #173 
https://github.com/user-attachments/assets/7b6cf129-6b2d-4c3d-96e1-4d104868d950

[Chore] 랭킹 페이지 api연결

---

src/App.tsx
src/api/rank/rank.api.ts
src/api/register/register.ts
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx
src/components/watchList/WatchList.tsx
src/pages/Detail.tsx
src/types/Rank.ts

Chore#174 세부페이지 api 연결

---

src/api/rank/rank.api.ts
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx
src/types/Rank.ts

Feature/#177 팀별 바 색상 변경

---

src/api/auth/auth.api.ts
src/components/passwordReset/Confirmpassword.tsx
src/components/passwordReset/VerificationCode.tsx
src/components/signup/Profile.tsx
src/components/signup/TeamSelect.tsx
src/components/signup/VerificationCode.tsx
src/pages/Home.tsx
src/pages/Login.tsx

Refactor/#182 인증api 수정

---

src/api/game/game.ts
src/api/register/register.ts
src/pages/register/RegisterForm.tsx

직관경기등록, 경기목록 API 에러 추가
closes #179

Chore/#179 직관경기등록, 경기목록 API 에러 추가

---

src/components/dailyMatch/DailyMatch.tsx
src/pages/register/RegisterForm.tsx
src/pages/register/SelectMatch.tsx
src/utils/setCheerTeamFirst.ts

[chore/#185] 직관 등록 수정

---

src/components/ranking/RankingTab.tsx

🎨 이미지 안뜸 해결

---

src/components/info/cheerSong/CheerSongList.tsx
src/pages/SearchCheerSong.tsx

Chore/#192 좋아요 최종수정

---

.eslintrc.cjs
src/api/home/home.api.ts
src/components/main/DonutChart.tsx
src/components/ranking/RankBar.tsx
src/pages/main/Rate.tsx
src/types/Record.ts

Feature/#184 승률 차트 생성

---

src/api/register/register.ts
src/components/common/Calendar.tsx
src/components/dailyMatch/DailyMatch.tsx
src/components/todayMatch/TodayMatchItem.tsx
src/components/todayMatch/TodayMatchList.tsx
src/components/watchList/GalleryTab/GalleryTab.tsx
src/components/watchList/WatchList.tsx
src/pages/main/Main.tsx
src/pages/register/RegisterForm.tsx
src/utils/findCheerTeam.ts
src/utils/setCheerTeamFirst.ts

Chore/#196 ♻️ 각종 오류 수정

---

package-lock.json
package.json
src/App.tsx
src/api/home/home.api.ts
src/components/main/CircleChart.tsx
src/components/main/DonutChart.tsx
src/pages/main/DetailRate.tsx
src/pages/main/Rate.tsx

Feature/#195 파이차트 추가

---

src/App.tsx
src/components/main/CircleChart.tsx
src/components/ranking/RankBar.tsx

{Chore] 차트 오류 수정

---

src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankingTab.tsx

[Chore] 바 랭킹 수정

---

src/components/main/CircleChart.tsx
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx
src/types/Rank.ts

[Chore] 차트수정

---

index.html
package-lock.json
package.json
src/components/info/cheerSong/CheerSongList.tsx
src/components/info/cheerSong/CheerSongPage.tsx
src/components/passwordReset/EmailValid.tsx
src/components/signup/EmailValid.tsx
src/pages/SearchCheerSong.tsx
src/pages/main/Rate.tsx

Feature/#203 이미지저장, 카톡공유

---

src/components/ranking/RankBar.tsx

[Chore] 바 색상 수정

---

src/components/ranking/RankPopup.tsx

[Chore] 팝업 드래그 수정

---

src/components/info/cheerSong/TeamList.tsx
src/components/info/map/LocationButton.tsx
src/components/info/map/Map.tsx
src/components/info/map/ParkingInfoPage.tsx
src/components/info/map/StadiumList.tsx

Chore/#216 멘토링 피드백 반영

---

package-lock.json
package.json
src/App.tsx
src/api/register/register.ts
src/components/common/Calendar.tsx
src/components/common/MonthNav.tsx
src/components/watchList/ListTab/ListTab.tsx
src/components/watchList/WatchList.tsx
src/hooks/useGame.tsx
src/hooks/useRegisteredGame.tsx
src/pages/main/Main.tsx
src/pages/register/SelectMatch.tsx

데브툴 추가
month 변경 시 데이터 요청
직관등록 시 현재 자기가 등록한 직관경기 아이콘 추가 및 경기 클릭 막기
closes #211 
closes #212 
closes #213

Chore/#211 자잘한거 수정하기

---

src/components/common/ToolTip.tsx
src/components/info/map/Map.tsx
src/pages/Info.tsx

✨ 지도리스트 클릭시 인포윈도우 열기

---

package-lock.json
package.json
src/components/common/ToolTip.tsx
src/pages/main/Rate.tsx

✨ 앱에서 이미지 다운로드 안되는문제 해결

---

src/components/common/Calendar.tsx
src/components/common/MonthNav.tsx
src/components/watchList/GalleryTab/GalleryTab.tsx
src/components/watchList/ListTab/ListTab.tsx
src/components/watchList/WatchList.tsx

직관리스트에서 month 변경 시 컴포넌트끼리 공유가 되지 않던 현상 해결
최대 month를 현재 month로 수정

Fix 직관 리스트 달력 및 MonthNav 수정

---

src/App.tsx
src/components/common/GameListItem.tsx
src/components/common/Loading.tsx
src/components/common/MonthNav.tsx
src/components/modal/Popup.tsx
src/components/todayMatch/TodayMatchItem.tsx
src/components/watchList/GalleryTab/GalleryTab.tsx
src/components/watchList/WatchList.tsx
src/hooks/useGame.tsx
src/pages/detail/Detail.tsx
src/pages/register/SelectMatch.tsx

- 경기 선택 시 로딩 추가 및 세부 페이지 수정 관련 작업을 수행했습니다.
- 팝업, 갤러리, 경기 등록 헤더 등 다양한 UI/UX 개선 사항을 포함했습니다.

Fix 버그들 수정

---

src/components/mypage/ProfileButtons.tsx
src/components/mypage/WithDrawPopup.tsx

[Refactor] 회원탈퇴 모달 구현

---

.eslintrc.cjs
src/App.tsx
src/components/common/ErrorBoundary.tsx
src/components/common/SearchBar.tsx
src/components/info/cheerSong/CheerSongList.tsx
src/components/info/cheerSong/CheerSongPage.tsx
src/components/info/cheerSong/TeamList.tsx
src/components/info/map/Map.tsx
src/components/info/map/ParkingInfoPage.tsx
src/components/info/map/ParkingList.tsx
src/components/info/map/StadiumList.tsx
src/components/info/map/ZoomButton.tsx
src/components/layout/Layout.tsx
src/pages/Error.tsx
src/pages/Info.tsx
src/pages/NotFound.tsx
src/pages/SearchCheerSong.tsx

맵, 무한스크롤, 검색바 리팩토링
에러바운더리와, 404페이지 추가했습니다
에러바운더리의 목적은 에러의 종류에는
1. api에러
2. 리액트 렌더시 런타임에러
3. 이벤트핸들러에러 
이렇게 3종류가 있는데 api에러는 보통 catch문에서 해결하는게 좋다고 하고, 저희 리액트쿼리를 쓰다보니 isError와 같은 에러 인터페이스가 잘되어있기도 해서 단순 리액트 렌더시 런타임에러 터질때 용도로 사용할 에러바운더리 추가했습니다

♻️ 맵, 무한스크롤, 검색바 리팩토링

---

src/components/mypage/Profile.tsx
src/components/mypage/ProfileButtons.tsx
src/components/mypage/ProfileChange.tsx
src/components/mypage/TeamChange.tsx

[Chore] 마이페이지 디자인 수정

---

src/App.tsx
src/components/mypage/ProfileButtons.tsx
src/components/mypage/TeamChange.tsx
src/components/ranking/MyRankComp.tsx
src/components/ranking/RankBar.tsx
src/components/ranking/RankPopup.tsx
src/components/ranking/RankTextComp.tsx
src/components/ranking/RankingTab.tsx

Chore/#260 랭킹 디자인 변경

---

src/components/info/cheerSong/CheerSongList.tsx
src/components/info/cheerSong/CheerSongPage.tsx
src/components/info/cheerSong/TeamList.tsx

💄 디자인 qa최종 수정

---

src/api/auth/auth.api.ts
src/components/info/cheerSong/CheerSongPage.tsx
src/components/info/map/ParkingInfoPage.tsx

♻️ 에러바운더리, 에러 처리 추가

---

src/components/ranking/RankBar.tsx

[Chore] 글짜 찌그러짐

---

src/components/signup/Profile.tsx

Chore/#264 프로필 건너뛰기 기능 추가

---

src/pages/main/Main.tsx
src/pages/main/Rate.tsx
src/utils/getFairyImg.ts

이미지 파일 png -> webp 변경
`<picture>`태그를 이용해서 webp를 지원하지 않는 IE에서는 png를 볼 수 있게 해주었습니다.
closes #276

Refactor/#276 이미지 파일 png -> webp 변경

---

index.html
package-lock.json
package.json
public/robots.txt
src/main.tsx
src/pages/Info.tsx
src/pages/Ranking.tsx
src/pages/helmets/DetailHelmet.tsx
src/pages/main/Main.tsx

react-helmet 추가 후 각 페이지에 적용
robots.txt 추가

SEO 개선 / react-helmet 추가

---

package-lock.json
package.json
vite.config.js
vite.config.ts

prerenderer 라이브러리 설치 후 적용하였습니다.
SPA 특성상 빈 index.html을 보여주지만 해당 라이브러리를 추가 함으로써 
빌드 시 동적으로 만들어진 페이지를 셀프로 크롤링해서 정적페이지인 html을 만들어 주게 됩니다. 성능적으로는 어떻게 될 지 좀 더 지켜봐야 할 듯 합니다.

SEO개선 / prerenderer 적용

---

.puppeteer.cjs
index.html
netlify.toml
package-lock.json
package.json
src/RouteChangeTracker.ts
src/components/common/Footer.tsx
src/components/layout/Layout.tsx
src/components/signup/TeamSelect.tsx
src/env.d.ts
src/pages/Home.tsx
src/pages/main/Main.tsx
src/pages/main/Rate.tsx
src/pages/register/RegisterForm.tsx
src/router/Router.tsx
src/utils/sendGaEvent.ts

GA를 index.html에서 스크립트 추가하지않고 react-ga4 라이브러리를 추가했습니다
그리고 클릭이벤트에 대한 정보 제공 할 수 있도록 유틸함수를 추가했습니다.
- [x ] 클릭이벤트 정보 ga로 제공
closes #282

Chore/#282 react-ga4 추가

---

index.html
src/components/info/map/Map.tsx
src/pages/Info.tsx

Chore/#284 지도 페이지 라이트하우스 개선

---

package-lock.json
package.json
src/components/info/cheerSong/CheerSongPage.tsx
src/components/info/map/Map.tsx
src/components/info/map/ParkingInfoPage.tsx
src/components/info/map/useNaverMaps.ts
src/pages/CheersongDetail.tsx
src/pages/SearchCheerSong.tsx
src/style/global.ts
vite.config.ts

Chore/#288 라이트 하우스 성능개선 추가

---

index.html
src/components/info/cheerSong/CheerSongPage.tsx
src/hooks/useIntersectionObserver.ts
src/pages/SearchCheerSong.tsx

Chore/#288 인터섹션옵저버 훅으로 분리

---

src/api/register/register.ts
src/components/dailyMatch/DailyMatchItem.tsx
src/components/mypage/ProfileChange.tsx
src/pages/MyPage.tsx
src/pages/detail/Detail.tsx
src/pages/register/RegisterForm.tsx
src/pages/register/SelectMatch.tsx
src/pages/register/SelectMatchCalendar.tsx
src/pages/register/dailyMatch/DailyMatch.tsx
src/pages/register/dailyMatch/DailyMatchItem.tsx
src/utils/uploadImg.ts

프로필 이미지 업로드 기능을 presigned URL 방식으로 변경하고, 이미지 업로드 엔드포인트를 분기 처리했습니다.

Feat : 프리사인드url 적용
